# Generated by Django 2.1.7 on 2019-06-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('home', 'Home'), ('work', 'Work')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('website', models.CharField(max_length=50)),
                ('bdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
                ('number_type', models.CharField(choices=[('mobile', 'Mobile'), ('tel', 'Telephone'), ('fax', 'Fax')], max_length=6)),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phonebook.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phonebook.Contact'),
        ),
    ]
