# Generated by Django 2.1.7 on 2019-08-02 09:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('street', models.TextField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('home', 'Home'), ('work', 'Work')], max_length=6)),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sur Name')),
                ('nick_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nick Name')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Company')),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('is_favourite', models.BooleanField(default=False, verbose_name='Favourite')),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='ContactNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.CharField(max_length=13)),
                ('number_type', models.CharField(choices=[('mobile', 'Mobile'), ('tel', 'Telephone'), ('fax', 'Fax')], default='mobile', max_length=6)),
                ('contact_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_ids', to='phonebook.Contact')),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phonebook.Contact'),
        ),
    ]
