# Generated by Django 2.1.7 on 2019-06-07 05:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='bdate',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nick_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nick Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactno',
            name='number_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tel', 'Telephone'), ('fax', 'Fax')], default='mobile', max_length=6),
        ),
    ]
