# Generated by Django 2.1.7 on 2019-06-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20190624_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name='Favourite'),
        ),
    ]
