# Generated by Django 2.1.7 on 2019-07-10 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_contact_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactno',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phonebook.Contact'),
        ),
    ]
