# Generated by Django 2.1.7 on 2019-07-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_auto_20190711_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactno',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_ids', to='phonebook.Contact'),
        ),
    ]
